require_relative 'rails_lite/controller_base'
require_relative 'rails_lite/router'
require_relative 'active_record_lite/associatable'
require_relative '../app/models/status'
require_relative '../app/controllers/statuses_controller'